name: "Orb"
description: "Orb sensor to continuously monitor network responsiveness and reliability."
version: "1.4.4"
slug: "orb_homeassistant"
init: false
host_network: true
image: "orbforge/orb-ha"
environment:
 ORB_DATA_DIR: /data
arch:
  - aarch64
  - amd64
  - armv7
boot: auto
services:
  - mqtt:need
options:
  mqtt_push: false
  mqtt_frequency: 5
  mqtt_debug: false
schema:
  mqtt_push: bool
  mqtt_frequency: int(1,120)
  mqtt_debug: bool
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: password?
